services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    

  backend: 
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:secret@database:5432/postgres
    depends_on:
       database:
         condition: service_healthy
  
  websocket:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.websocket
    ports:
      - "8000:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:secret@database:5432/postgres
    depends_on:
      - backend

  
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
      args:
        - DATABASE_URL=postgresql://postgres:secret@database:5432/postgres
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:secret@database:5432/postgres
    depends_on:
      - backend