FROM   node:24-alpine AS builder


ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

ARG BETTER_AUTH_URL
ENV BETTER_AUTH_URL=${BETTER_AUTH_URL}

ARG BETTER_AUTH_SECRET
ENV BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}

ARG PUBLIC_TRUSTED_FRONTED_BETTER_AUTH_URL
ENV PUBLIC_TRUSTED_FRONTED_BETTER_AUTH_URL=${PUBLIC_TRUSTED_FRONTED_BETTER_AUTH_URL}

WORKDIR /app

COPY package-lock.json   . 
COPY package.json        .
COPY turbo.json          .

COPY apps/http-server/package.json                ./apps/http-server/package.json
COPY packages/db/package.json                   ./packages/db/package.json
COPY packages/auth/package.json                 ./packages/auth/package.json
COPY packages/validation/package.json           ./packages/validation/package.json
COPY packages/typescript-config/package.json    ./packages/typescript-config/package.json

RUN npm install -g npm@11.16.0
RUN npm install

COPY apps/http-server               ./apps/http-server
COPY packages/auth                ./packages/auth
COPY packages/db                  ./packages/db
COPY packages/validation          ./packages/validation
COPY packages/typescript-config    ./packages/typescript-config

RUN npm run generate:db
RUN npm run build:db
RUN npm run build:auth
RUN npm run build:validation
RUN npm run build:backend


FROM   node:24-alpine 


ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

ARG BETTER_AUTH_URL
ENV BETTER_AUTH_URL=${BETTER_AUTH_URL}

ARG BETTER_AUTH_SECRET
ENV BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}

ARG PUBLIC_TRUSTED_FRONTED_BETTER_AUTH_URL
ENV PUBLIC_TRUSTED_FRONTED_BETTER_AUTH_URL=${PUBLIC_TRUSTED_FRONTED_BETTER_AUTH_URL}

WORKDIR /app

COPY package-lock.json   . 
COPY package.json        .
COPY turbo.json          .

COPY apps/http-server/package.json                ./apps/http-server/package.json
COPY packages/db/package.json                   ./packages/db/package.json
COPY packages/auth/package.json                 ./packages/auth/package.json
COPY packages/validation/package.json           ./packages/validation/package.json
COPY packages/typescript-config/package.json    ./packages/typescript-config/package.json

RUN npm install -g npm@11.16.0
RUN npm install --omit=dev


COPY --from=builder app/apps/http-server/dist               ./apps/http-server/dist
COPY --from=builder app/packages/auth/dist                ./packages/auth/dist
COPY --from=builder app/packages/db/dist                  ./packages/db/dist
COPY --from=builder app/packages/db/prisma                ./packages/db/prisma
COPY --from=builder app/packages/db/prisma.config.ts      ./packages/db/prisma.config.ts
COPY --from=builder app/packages/validation/dist               ./packages/validation/dist
COPY --from=builder app/packages/typescript-config        ./packages/typescript-config


EXPOSE 3000


CMD [ "sh", "-c", "npm run migrate:db && npm run start:backend"  ]





